/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * <h2><center>&copy; Copyright (c) 2020 STMicroelectronics.
 * All rights reserved.</center></h2>
 *
 * This software component is licensed by ST under BSD 3-Clause license,
 * the "License"; You may not use this file except in compliance with the
 * License. You may obtain a copy of the License at:
 *                        opensource.org/licenses/BSD-3-Clause
 *
 ******************************************************************************
 */

#include <stdint.h>
#include "STM32F4XX.h"
#include "STM32FXX_GPIO_Driver.h"
void delay(void)
{
for(uint32_t i=0;i<500000;i++);
}
int main()
{
GPIO_HANDLE_t GpioLed;
GpioLed.pGPIOx=GPIOD;
GpioLed.GPIO_PIN_CONFIG.GPIO_PinNumber=GPIO_PIN_NUM_14;
GpioLed.GPIO_PIN_CONFIG.GPIO_PinMode=GPIO_PIN_MODE_Output;
GpioLed.GPIO_PIN_CONFIG.GPIO_PinSpeed=GPIO_PinSpeed_High;
GpioLed.GPIO_PIN_CONFIG.GPIO_PinOPType=GPIO_PinOPType_PP;
GpioLed.GPIO_PIN_CONFIG.GPIO_PinPuPdControl=GPIO_PinPuPdControl_PU;
GPIO_PeriClockControl(GPIOD,ENABLE);
GPIO_Init(&GpioLed);
while(1)
 {
	GPIO_ToggleOutputPin(GPIOD,14);
	delay();
 }
}
